project_id = "noulbzfsrupgjgacrwem"

[auth]
enabled = true
external_url = ""
additional_redirect_urls = ["https://ibbdnfcefchxtpvjvczj.lovableproject.com"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
shadow_port = 54320
port = 54322

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[storage]
enabled = true
file_size_limit = "50MiB"

[edge-runtime]
enabled = true
port = 54323

[analytics]
enabled = false

[functions.apollo-company-search]
verify_jwt = true

[functions.company-enrichment]
verify_jwt = true

[functions.email-generation]
verify_jwt = true

[functions.kdm-discovery]
verify_jwt = true

[functions.lead-enrichment]
verify_jwt = true

[functions.lead-scoring]
verify_jwt = true

[functions.lead-scraping]
verify_jwt = true

[functions.rate-limiter]
verify_jwt = true

[functions.enhanced-lead-mining]
verify_jwt = true

[functions.cancel-mining-session]
verify_jwt = true

[functions.cleanup-mining-sessions]
verify_jwt = true

[functions.apollo-usage-check]
verify_jwt = true

[functions.send-smtp-email]
verify_jwt = true

[functions.signal-generation]
verify_jwt = true